# Common configuration for all environments
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# Development environment configuration using SQLite
development:
  <<: *default
  database: db/development.sqlite3

# Test environment configuration using SQLite
test:
  <<: *default
  database: db/test.sqlite3

# Production environment configuration using PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
